dist: trusty
sudo: false

language: cpp

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
    - eigen
    
branches:
  only:
    - master

env:
  - DMP_BUILD_TYPE=Debug BUILD_SHARED_LIBS=ON
  - DMP_BUILD_TYPE=Debug BUILD_SHARED_LIBS=OFF
  - DMP_BUILD_TYPE=Release BUILD_SHARED_LIBS=ON
  - DMP_BUILD_TYPE=Release BUILD_SHARED_LIBS=OFF
  
script:
  - mkdir install
  - mkdir build;cd build
  - cmake -DCMAKE_BUILD_TYPE=$DMP_BUILD_TYPE -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS -DCMAKE_INSTALL_PREFIX=../install ..
  - make -j2 VERBOSE=1
  - make install
